# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CALCULATOR(object):
    def setupUi(self, CALCULATOR):
        CALCULATOR.setObjectName("CALCULATOR")
        CALCULATOR.resize(512, 612)
        self.centralwidget = QtWidgets.QWidget(CALCULATOR)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.obj_0 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_0.setGeometry(QtCore.QRect(40, 440, 150, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_0.setFont(font)
        self.obj_0.setStyleSheet("background-color: rgb(33, 255, 163);")
        self.obj_0.setObjectName("obj_0")
        self.obj_equal = QtWidgets.QPushButton(self.centralwidget)
        self.obj_equal.setGeometry(QtCore.QRect(210, 440, 150, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_equal.setFont(font)
        self.obj_equal.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.obj_equal.setObjectName("obj_equal")
        self.obj_1 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_1.setGeometry(QtCore.QRect(40, 340, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_1.setFont(font)
        self.obj_1.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_1.setObjectName("obj_1")
        self.obj_2 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_2.setGeometry(QtCore.QRect(150, 340, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_2.setFont(font)
        self.obj_2.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_2.setObjectName("obj_2")
        self.obj_3 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_3.setGeometry(QtCore.QRect(260, 340, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_3.setFont(font)
        self.obj_3.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_3.setObjectName("obj_3")
        self.obj_4 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_4.setGeometry(QtCore.QRect(40, 240, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_4.setFont(font)
        self.obj_4.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_4.setObjectName("obj_4")
        self.obj_5 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_5.setGeometry(QtCore.QRect(150, 240, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_5.setFont(font)
        self.obj_5.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_5.setObjectName("obj_5")
        self.obj_6 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_6.setGeometry(QtCore.QRect(260, 240, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_6.setFont(font)
        self.obj_6.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_6.setObjectName("obj_6")
        self.obj_7 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_7.setGeometry(QtCore.QRect(40, 140, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_7.setFont(font)
        self.obj_7.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_7.setObjectName("obj_7")
        self.obj_9 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_9.setGeometry(QtCore.QRect(260, 140, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_9.setFont(font)
        self.obj_9.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_9.setObjectName("obj_9")
        self.obj_8 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_8.setGeometry(QtCore.QRect(150, 140, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_8.setFont(font)
        self.obj_8.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_8.setObjectName("obj_8")
        self.obj_10 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_10.setGeometry(QtCore.QRect(370, 340, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_10.setFont(font)
        self.obj_10.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_10.setObjectName("obj_10")
        self.obj_11 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_11.setGeometry(QtCore.QRect(370, 240, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_11.setFont(font)
        self.obj_11.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_11.setObjectName("obj_11")
        self.obj_12 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_12.setGeometry(QtCore.QRect(370, 140, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_12.setFont(font)
        self.obj_12.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_12.setObjectName("obj_12")
        self.obj_13 = QtWidgets.QPushButton(self.centralwidget)
        self.obj_13.setGeometry(QtCore.QRect(370, 440, 100, 90))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.obj_13.setFont(font)
        self.obj_13.setStyleSheet("background-color: rgb(255, 179, 0);")
        self.obj_13.setObjectName("obj_13")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 60, 431, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(215, 255, 249);")
        self.label.setObjectName("label")
        CALCULATOR.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CALCULATOR)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 26))
        self.menubar.setObjectName("menubar")
        CALCULATOR.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CALCULATOR)
        self.statusbar.setObjectName("statusbar")
        CALCULATOR.setStatusBar(self.statusbar)

        self.retranslateUi(CALCULATOR)
        QtCore.QMetaObject.connectSlotsByName(CALCULATOR)

        self.add_functions()

        self.is_equal = False

    def retranslateUi(self, CALCULATOR):
        _translate = QtCore.QCoreApplication.translate
        CALCULATOR.setWindowTitle(_translate("CALCULATOR", "CACULATOR"))
        self.obj_0.setText(_translate("CALCULATOR", "0"))
        self.obj_equal.setText(_translate("CALCULATOR", "="))
        self.obj_1.setText(_translate("CALCULATOR", "1"))
        self.obj_2.setText(_translate("CALCULATOR", "2"))
        self.obj_3.setText(_translate("CALCULATOR", "3"))
        self.obj_4.setText(_translate("CALCULATOR", "4"))
        self.obj_5.setText(_translate("CALCULATOR", "5"))
        self.obj_6.setText(_translate("CALCULATOR", "6"))
        self.obj_7.setText(_translate("CALCULATOR", "7"))
        self.obj_9.setText(_translate("CALCULATOR", "9"))
        self.obj_8.setText(_translate("CALCULATOR", "8"))
        self.obj_10.setText(_translate("CALCULATOR", "*"))
        self.obj_11.setText(_translate("CALCULATOR", "-"))
        self.obj_12.setText(_translate("CALCULATOR", "+"))
        self.obj_13.setText(_translate("CALCULATOR", "/"))
        self.label.setText(_translate("CALCULATOR", " "))

    def add_functions(self):
        self.obj_0.clicked.connect(
            lambda: self.write_number(self.obj_0.text()))
#        self.obj_equal.clicked.connect(
#            lambda: self.write_number(self.obj_equal.text()))
        self.obj_1.clicked.connect(
            lambda: self.write_number(self.obj_1.text()))
        self.obj_2.clicked.connect(
            lambda: self.write_number(self.obj_2.text()))
        self.obj_3.clicked.connect(
            lambda: self.write_number(self.obj_3.text()))
        self.obj_4.clicked.connect(
            lambda: self.write_number(self.obj_4.text()))
        self.obj_5.clicked.connect(
            lambda: self.write_number(self.obj_5.text()))
        self.obj_6.clicked.connect(
            lambda: self.write_number(self.obj_6.text()))
        self.obj_7.clicked.connect(
            lambda: self.write_number(self.obj_7.text()))
        self.obj_8.clicked.connect(
            lambda: self.write_number(self.obj_8.text()))
        self.obj_9.clicked.connect(
            lambda: self.write_number(self.obj_9.text()))
        self.obj_10.clicked.connect(
            lambda: self.write_number(self.obj_10.text()))
        self.obj_11.clicked.connect(
            lambda: self.write_number(self.obj_11.text()))
        self.obj_12.clicked.connect(
            lambda: self.write_number(self.obj_12.text()))
        self.obj_13.clicked.connect(
            lambda: self.write_number(self.obj_13.text()))
        self.obj_equal.clicked.connect(self.results)

    def write_number(self, number):
        if self.label.text() == "0" or self.is_equal:
            self.label.setText(number)
            self.is_equal = False
        else:
            self.label.setText(self.label.text() + number)

    def results(self):
        res = eval(self.label.text())
        self.label.setText('Result: ' + str(res))
        self.is_equal = True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CALCULATOR = QtWidgets.QMainWindow()
    ui = Ui_CALCULATOR()
    ui.setupUi(CALCULATOR)
    CALCULATOR.show()
    sys.exit(app.exec_())
